### PR TITLE
Export texture frames

### PR DESCRIPTION
**Pull request by Doomlazer**

### CODE REVIEW

**Comment by deckarep** [comment]
@Doomlazer  - I'm seeing conflicts again but I didn't push anything.

**Comment by Doomlazer** [comment]
I don't know why that keeps happening, but I resolved them. Would you mind adding me to the repo so I can push directly?

**Comment by deckarep** [comment]
Absolutely!

**Comment by deckarep** [comment]
BTW, it looks like your fork is out of date and missing one of my commits which is probably why you keep getting a merge conflict. If you get my changes and true up your fork all should be good going forward.

**Pull request merged**
